spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  datasource:
    username: cailangrott
    password: Caica122014
    url: jdbc:mysql://riaceci.cmzh6h3jlyws.sa-east-1.rds.amazonaws.com:3306/riaceci
    driverClassName: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 8080

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}